import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#1a1a1a",
    paddingTop: 20,
  },
  header: {
    marginBottom: 20,
    alignItems: "center",
    marginTop: 20,
  },
  headerText: {
    fontSize: 32,
    fontWeight: "bold",
    color: "#fff",
    textAlign: "center",
  },
  subHeaderText: {
    fontSize: 20,
    color: "#666",
    textAlign: "center",
    marginTop: 5,
  },
  headerWithBack: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 20,
    marginBottom: 20,
  },
  headerCenter: {
    flex: 1,
    alignItems: "center",
  },
  backArrow: {
    padding: 10,
    marginLeft: -10,
  },
  cardContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  swipeableCard: {
    width: "100%",
    aspectRatio: 0.7,
    backgroundColor: "#2a2a2a",
    borderRadius: 20,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 5,
    },
    shadowOpacity: 0.5,
    shadowRadius: 6.27,
    elevation: 10,
  },
  fullCard: {
    width: "100%",
    height: "100%",
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    padding: 30,
    backgroundColor: "#2a2a2a",
    position: "relative",
  },
  cardText: {
    fontSize: 36,
    textAlign: "center",
    color: "#fff",
    fontWeight: "500",
  },
  flipHint: {
    position: "absolute",
    bottom: 20,
    fontSize: 16,
    color: "#666",
    textAlign: "center",
  },
  counter: {
    textAlign: "center",
    fontSize: 16,
    color: "#666",
    marginVertical: 20,
  },
  studyButton: {
    backgroundColor: "#4CAF50",
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 10,
    marginHorizontal: 20,
    marginBottom: 20,
  },
  buttonText: {
    color: "white",
    fontSize: 18,
    fontWeight: "600",
    textAlign: "center",
  },
  editButton: {
    padding: 8,
    marginLeft: 8,
    backgroundColor: "rgba(76, 175, 80, 0.1)",
    borderRadius: 8,
  },
  deleteButton: {
    position: "absolute",
    top: 20,
    right: 20,
    padding: 10,
  },
  addCardButton: {
    padding: 10,
    marginRight: -10,
  },
  button: {
    backgroundColor: "#2196F3",
    padding: 15,
    borderRadius: 10,
    alignItems: "center",
    marginVertical: 5,
  },
  fullWidthButton: {
    marginHorizontal: 20,
  },
  studyStats: {
    marginHorizontal: 20,
    marginBottom: 20,
    alignItems: "center",
  },
  studyCounter: {
    fontSize: 16,
    color: "#666",
  },
  correctStat: {
    color: "#4CAF50",
    fontWeight: "bold",
  },
  incorrectStat: {
    color: "#FF3B30",
    fontWeight: "bold",
  },
  deckList: {
    paddingHorizontal: 20,
    marginVertical: 20,
  },
  deckItemContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#2a2a2a",
    padding: 15,
    borderRadius: 15,
    marginBottom: 12,
    maxWidth: 500,
    alignSelf: "center",
    width: "100%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  deckItem: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
  },
  deckContent: {
    flex: 1,
  },
  deckTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#fff",
    marginBottom: 4,
  },
  deckSubtitle: {
    fontSize: 14,
    color: "#999",
  },
  deckDeleteButton: {
    padding: 8,
    marginLeft: 15,
    backgroundColor: "rgba(255, 59, 48, 0.1)",
    borderRadius: 8,
  },
  addButton: {
    backgroundColor: "#4CAF50",
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 25,
    marginTop: 10,
    marginBottom: 30,
    alignSelf: "center",
    minWidth: 180,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  addButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    padding: 20,
  },
  modalContent: {
    backgroundColor: "#2a2a2a",
    borderRadius: 20,
    padding: 30,
    width: "100%",
    maxWidth: 400,
    alignItems: "stretch",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.5,
    shadowRadius: 3.84,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 20,
    textAlign: "center",
    color: "#fff",
  },
  input: {
    borderWidth: 1,
    borderColor: "#444",
    borderRadius: 10,
    padding: 15,
    marginBottom: 20,
    width: "100%",
    fontSize: 16,
    backgroundColor: "#333",
    color: "#fff",
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
  },
  formContainer: {
    width: "100%",
  },
  inputLabel: {
    fontSize: 16,
    marginBottom: 5,
    color: "#fff",
  },
  autoFeaturesContainer: {
    backgroundColor: "#2a2a2a",
    padding: 15,
    borderRadius: 10,
    marginBottom: 20,
  },
  autoFeatureRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  languageItemContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#2a2a2a",
    padding: 15,
    borderRadius: 15,
    marginHorizontal: 20,
    marginBottom: 12,
    maxWidth: 500,
    alignSelf: "center",
    width: "100%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  languageContent: {
    flex: 1,
  },
  languageTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: "#fff",
    marginBottom: 4,
  },
  languageSubtitle: {
    fontSize: 14,
    color: "#999",
  },
  languageDeleteButton: {
    padding: 8,
    marginLeft: 12,
    backgroundColor: "rgba(255, 59, 48, 0.1)",
    borderRadius: 8,
  },
  emptyDeckText: {
    fontSize: 18,
    textAlign: "center",
    color: "#999",
    marginVertical: 30,
  },
  emptyDeckButtons: {
    flexDirection: "row",
    justifyContent: "space-around",
    width: "100%",
  },
  completionContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  completionText: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#fff",
    marginTop: 20,
  },
  completionSubtext: {
    fontSize: 16,
    color: "#999",
    textAlign: "center",
    marginTop: 10,
    marginBottom: 30,
  },
  arrowButton: {
    position: "absolute",
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    top: "60%",
    marginTop: -20,
    zIndex: 10,
  },
  leftArrow: {
    left: 20,
    backgroundColor: "#FF3B30",
  },
  rightArrow: {
    right: 20,
    backgroundColor: "#4CAF50",
  },
  translatingContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  translatingText: {
    color: "#4CAF50",
    marginLeft: 10,
    fontSize: 14,
  },
  headerTitleContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    color: "#fff",
    fontSize: 18,
  },
});
